### ISSUE TITLE
Error in patching

### ISSUE THREAD

**Issue by mjs520** [chris1111/Patch-HD4000-Monterey#3]
![IMG_20210626_112803](https://user-images.githubusercontent.com/26852845/123500777-09448280-d673-11eb-9fe1-71a171959178.jpg)
![IMG_20210626_113917](https://user-images.githubusercontent.com/26852845/123500797-2e38f580-d673-11eb-89ad-ea14e7bf8c3b.jpg)

**Comment by chris1111** [comment]
Probably an apple events issue ? To reset full disk access privileges
Terminal
tccutil reset SystemPolicyAllFiles

then reboot
